FROM registry.redhat.io/rhel9/support-tools:latest

COPY tpm2-tools-5.2-7.el9.x86_64.rpm /

RUN rpm -ihv /tpm2-tools-5.2-7.el9.x86_64.rpm && \
    rm -f /tpm2-tools-5.2-7.el9.x86_64.rpm && \
    rm -rf /var/cache/yum /var/cache/dnf
